name: swinunet
family: Transformers
encoder: Swin

# I/O
image_size: ${project.image_size}
in_channels: ${data.in_channels}
out_channels: ${task.out_channels}

# Pretrained model
# IMPORTANT: Only file name, not full path
# can be null or "" to disable pretrained loading
pretrained_ckpt: swin_tiny_patch4_window7_224.pth

# Dropout rate
drop_rate: 0.0
# Drop path rate
drop_path_rate: 0.2
use_checkpoint: False

# Swin Transformer parameters
swin:
  final_upsample: expand_first
  patch_size: 4
  embed_dim: 96
  depths: [ 2, 2, 2, 2 ]
  decoder_depths: [ 1, 2, 2, 2]
  num_heads: [ 3, 6, 12, 24 ]
  window_size: 7
  mlp_ratio: 4.
  qkv_bias: True
  qk_scale: # None
  ape: False
  patch_norm: True