# Swin-Unet
architecture_name: swinunet
family: Transformers

# Model name
name: swinunet_patch${model.swin.patch_size}_window${model.swin.window_size}

# I/O
in_channels: ${dataset.in_channels}
out_channels: ${dataset.out_channels}
# Image Size
image_size: ${project.image_size}

# Dropout rate
drop_rate: 0.0
# Drop path rate
drop_path_rate: 0.2
use_checkpoint: False

# Pretrained ckpt
pretrained_ckpt: swin_tiny_patch4_window7_224.pth

# Swin Transformer parameters
swin:
  final_upsample: expand_first
  patch_size: 4
  # window_size: 7
  window_size: 8

  embed_dim: 96
  depths: [ 2, 2, 2, 2 ]
  decoder_depths: [ 1, 2, 2, 2]
  num_heads: [ 3, 6, 12, 24 ]
  mlp_ratio: 4.
  qkv_bias: True
  qk_scale: null
  ape: False
  patch_norm: True