# TransUNet: From https://github.com/Beckschen/TransUNet
architecture_name: transunet
family: Transformers

# Model name
name: transunet_resnet50_vit-b/16

classifier: seg

# I/O
out_channels: ${dataset.out_channels}
# Image Size
image_size: ${project.image_size}

# Pretrained ckpt
pretrained_ckpt: null

# Encoder
encoder: ResNet50
resnet:
  num_layers: [3, 4, 9]
  width_factor: 1

hidden_layers: 768
head_channels: 512

# Patch emb
patch_size: 16
patches:
    size: [16,16]
    grid: [14, 14]

# Transformer
transformer:
  mlp_dim: 3072
  num_heads: 12
  num_layers: 12
  attention_dropout_rate: 0.0
  dropout_rate: 0.1

#Decoder
decoder_channels: [256, 128, 64, 16]
skip_channels: [512, 256, 64, 16]
n_classes: 2
n_skip: 3

vis: False
zero_head: False
representation_size: null
resnet_pretrained_path: null