# Configs model inspection
name: inspect
# Model
model_name: ${model.name}
# Input
batch_size: 1
in_channels: ${dataset.in_channels}
image_size: ${dataset.image_size}

# Paths to export
export_path: ${paths.report_dir}/img_${dataset.image_size}_inspect_bs${inspect.batch_size}/${model.name}

# Path to save summary from torchinfo
summary_path: ${inspect.export_path}/torchsummary.txt

# Path to save onnx file
onnxx_path: ${inspect.export_path}/${model.name}_onnx.onnx
