# configs/dataset/isic2018.yaml
defaults:
  - augmentation
  - _self_

name: isic2018
task: binary
split: 7:3

# Data directory
root: ${paths.data_dir}/${dataset.name}
# Zip Data directory
archive_path: ${dataset.root}.zip

# I/O
in_channels: 3
out_channels: 1

# Image Size
image_size: ${project.image_size}

norm:
  stats:
    train: { mean: 157.561, std: 26.706 }
    val:   { mean: 149.034, std: 32.022 }
