# configs/dataset/isic2017.yaml
defaults:
  - augmentation
  - _self_

name: isic2017
task: binary

# Data directory
root: ${paths.data_dir}/${dataset.name}
# Zip Data directory
archive_path: ${dataset.root}.zip # e.g. /data/isic2017.zip

# I/O
in_channels: 3
out_channels: 1

# Image Size
image_size: ${project.image_size}

norm:
  # ---- MODE SWITCH ----
  # vmunet: reproduce your thesis/VM-UNet preprocessing (split-specific stats + minmax)
  # standard_train: train stats for ALL splits + per-channel + no minmax (best practice)
  # imagenet: common for pretrained backbones
  # none: no normalization (only scaling to [0,1])

  mode: vmunet

  # optional flag: use train stats for val as well (best practice)
  use_train_stats_for_all: false

  # Existing split-specific scalar stats (uint8 domain)
  stats:
    train: { mean: 157.561, std: 26.706 }
    val:   { mean: 149.034, std: 32.022 }


  # Optional for standard_train (per-channel, in [0,1] domain)
  # Fill these later by computing on train split only.
  train_stats_channel:
    mean: [0.7130480131349732, 0.6069051612218899, 0.5614104917723223]
    std: [0.15458055247033792, 0.16366840804634103, 0.18008193802702935]

  imagenet_stats:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
