# configs/config.yaml
defaults:
  - base
  - model: unet
  - dataset: isic2017
  - inspect: default
  - logging: mlflow
  - train: default
  - eval: default
  - _self_

project:
  # I/O
  batch_size: 16
  image_size: 256
  augmentation: True
  # Dataloaders
  num_workers: 1
  # Setup
  device: cuda
  seed: 42
  # Training
  epochs: 3
  use_pretrained_ckpt: False

  env: ${paths.repo_root}/environment.yml
